language: php

dist: trusty

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

install:
  - composer self-update
  - composer install

before_script:
  - echo $GIT_COMMIT_SHA
  - echo $GIT_BRANCH
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/cc-test-reporter
  - chmod a+x ~/cc-test-reporter
  - ~/cc-test-reporter before-build

script:
  - make build

after_script:
  - ~/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
