version: 2.1

commands:
  cc-reporter-pre:
    steps:
      - run:
          name: Download Code Climate test reporter
          command: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/cc-test-reporter
      - run:
          name: Make Code Climate test reporter executable
          command: chmod a+x ~/cc-test-reporter
      - run:
          name: Debug
          command: GIT_COMMIT_SHA=$CIRCLE_SHA1 GIT_BRANCH=$CIRCLE_BRANCH printenv
      - run:
          name: Initialise Code Climate test reporter
          command: GIT_COMMIT_SHA=$CIRCLE_SHA1 GIT_BRANCH=$CIRCLE_BRANCH ~/cc-test-reporter before-build
  cc-reporter-post:
    steps:
      - run:
          name: Send tests result to Code Climate
          command: ~/cc-test-reporter after-build --exit-code $?

  install-dependencies:
    steps:
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Install xdebug
          command: sudo -E install-php-extensions xdebug
      - run:
          name: Enable xdebug
          command: sudo -E docker-php-ext-enable xdebug

jobs:
  php-81:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - install-dependencies
      - cc-reporter-pre
      - run:
          name: Check coding style (PSR12)
          command: make phpcs
      - run:
          name: Run unit tests
          command: make phpunit
      - cc-reporter-post

workflows:
  ci:
    jobs:
      - php-81
