version: 2.1

jobs:
  php-81:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Check coding style (PSR12)
          command: make phpcs
      - run:
          name: Run unit tests
          command: make phpunit

workflows:
  ci:
    jobs:
      - php-81
